server:
  port: 8082
spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/appointments
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate.order_updates: true

appointment:
  fail:
    schedule: 0 23 * * *
